name: Run Unit Tests on PR to Master

# Trigger the workflow on pull request to the master branch
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the OS you want to run the job on
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests=false

      - name: Run Unit Tests
        run: ./mvnw test
